/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.openkengboy.validation;

import javax.validation.Valid;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.github.openkengboy.validation.model.BodyRequest;

@SpringBootApplication(exclude={DataSourceAutoConfiguration.class})
@RestController
public class App {
	
    public String greeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);
    }

    @PostMapping("/hello")
    public ResponseEntity<String> hello(@RequestBody @Valid BodyRequest test) {
        return ResponseEntity.ok(greeting() + ", " + test.getNameTest());
    }
    
    @GetMapping("/hello-test")
    public ResponseEntity<String> helloTest() {
        return ResponseEntity.ok(greeting());
    }
}
